# Generated by Django 5.2.17 on 2026-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
